[package]
name = "rust_learning"
version = "0.1.0"
authors = ["caoyong <edencaox@gmail.com>"]

[[bin]]
name = "guess"
path = "src/guess.rs"

[[bin]]
name = "mutable"
path = "src/mutable.rs"

[[bin]]
name = "shadow"
path = "src/shadowing.rs"

[[bin]]
name = "types"
path = "src/type.rs"

[dependencies]
rand = "0.5.5"